version: "3.4"

services:
  #  proxy reverso
  traefik:
    command:
      - --api
      - --docker
      - --logLevel=ERROR
      - --traefikLog.filePath=/logs/traefik.log
      - --traefikLog.format=json
      - --accessLog.filePath=/logs/access.log
      - --accessLog.format=json
      - --docker.domain=${DOMAIN}
      - --docker.watch=true
      - --docker.exposedbydefault=false
    volumes:
      - ./logs/traefik:/logs

  # servidor web para o back
  nginx:
    build:
      target: development
    volumes:
      - ./logs/nginx:/var/log/nginx

  # backend
  back:
    build:
      target: development
      args:
        - USERNAME=${USERNAMEDOCKER}

  # frontend
  front:
    build:
      target: development
    command: npm run start
    labels:
      - traefik.port=3000
      - traefik.frontend.rule=Host:front.${DOMAIN}
    volumes:
      - ./front:/app
      - /app/node_modules

  # SGBD
  phpmyadmin:
    container_name: ${APP_NAME}_phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.docker.network=mmh_external
      - traefik.tcp.rule=Host:phpmyadmin.${DOMAIN}
      - traefik.backend=phpmyadmin
    networks:
      - mmh_external
      - internal
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
    volumes:
      - sessions
    tty: true

volumes:
  sessions:
