version: "3.4"

networks:
  mmh_external:
    external: true
  internal:
    external: false

services:
  #  proxy reverso
  traefik:
    container_name: ${APP_NAME}_traefik
    image: traefik:${TRAEFIK_VERSION}
    ports:
      - 80:80
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:traefik.${DOMAIN}
      - traefik.frontend.auth.basic=${TRAEFIK_AUTH}
    networks:
      - mmh_external
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true

  # servidor web para o back
  nginx:
    container_name: ${APP_NAME}_nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      args:
        - UPSTREAM_CONTAINER=back
        - UPSTREAM_PORT=9000
    depends_on:
      - back
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:back.${DOMAIN}
      - traefik.docker.network=mmh_external
      - traefik.backend=back
    networks:
      - mmh_external
      - internal
    volumes:
      - ./back:/var/www
    tty: true

  # backend
  back:
    container_name: ${APP_NAME}_backend
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    depends_on:
      - traefik
      - mysql
    networks:
      - mmh_external
      - internal
    volumes:
      - ./back:/var/www
    tty: true

  # frontend
  front:
    container_name: ${APP_NAME}_frontend
    build:
      context: ./front
      dockerfile: Dockerfile
    depends_on:
      - traefik
      - back
    labels:
      - traefik.enable=true
      - traefik.docker.network=mmh_external
      - traefik.backend=front
    networks:
      - mmh_external
      - internal
    tty: true

  # banco de dados
  mysql:
    container_name: ${APP_NAME}_mysql
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    labels:
      - traefik.enable=true
      - traefik.port=3306
      - traefik.docker.network=internal
      - traefik.backend=mysql
    networks:
      - internal
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TIMEZONE=${TIMEZONE}
    volumes:
      - mysql:/var/lib/mysql
    tty: true

volumes:
  mysql:
